### ISSUE TITLE
Use different sandbox to test sync

### ISSUE THREAD

**Issue by zhongkairen** [zhongkairen/airtable-sync#10]
# Task list
- [x] #13
- [x] Create GitHub issues and project fields
- [x] Create separate tokens for Airtable
- [x] Create separate token for GitHub
- [x] #14

**Comment by zhongkairen** [comment]
https://airtable.com/app5c1A4u4zw1UbXN/tblma0DImG8wj84Va/viwS9ERBqHQVNRvsx?blocks=hide

base ID 
`app5c1A4u4zw1UbXN/tblma0DImG8wj84Va`

table ID
`tblma0DImG8wj84Va`

view ID
`viwS9ERBqHQVNRvsx`

**Comment by zhongkairen** [comment]
GitHub token
`AIRTABLE_SYNC_ISSUES_METADATA_R_PAT`
`airtable-sync.issues.metadata.r.pat`

**Comment by zhongkairen** [comment]
Airtable token
`AIRTABLE_SYNC_SANDBOX_PAT `
`airtable.records_wr.schema_base_r.sync_sandbox.pat`

**Comment by zhongkairen** [comment]
todo 
fix field type conversion
```python
    todo - generalize type conversion based on field type in table schema
    """

    def iso_date_parser(x): return datetime.strptime(x, "%Y-%m-%d")
    def iso_date_formatter(x): return x.strftime("%Y-%m-%d")
    """Parser used with values in response are handled"""
    _field_parser = {
        "Start Date": iso_date_parser,
        "Delivery Date": iso_date_parser,
        "Engineering Start Date": iso_date_parser,
        "Engineering Delivery Date": iso_date_parser,
    }
    """Formatter used when passing values to request"""
    _field_formatter = {
        "Start Date": iso_date_formatter,
        "Delivery Date": iso_date_formatter,
        "Engineering Start Date": iso_date_formatter,
        "Engineering Delivery Date": iso_date_formatter,
    }
```
